[book]
authors = ["Lachlan Deakin"]
language = "en"
multilingual = false
src = "src"
title = "The Rust zarrs Book"
description = "This book covers the zarrs Rust crate (and associated tools) for the Zarr storage format for multidimensional arrays and metadata"

[output.html]
# mathjax-support = false
git-repository-url = "https://github.com/LDeakin/zarrs_book"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
